### ISSUE TITLE
Home icon off-center

### ISSUE THREAD

**Issue by john-pettigrew** [john-pettigrew/roku-remote#4]
The home icon is off center. Probably just a CSS issue.

**Comment by pranav-prakash** [comment]
Seems centered to me. Is this not what you are seeing?

![image](https://cloud.githubusercontent.com/assets/10335022/6861866/d97363b8-d3fa-11e4-88f8-586053d3e6af.png)

**Comment by john-pettigrew** [comment]
Oh, must have just been me looking at it wrong and the shadows from the buttons.
